name: open_data_valuation
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.41.1
      - pandas==2.2.3
      - numpy==1.26.4
      - scikit-learn==1.5.2
      - matplotlib==3.9.2
      - seaborn==0.13.2
      - plotly==5.24.1
      - openpyxl==3.1.5
      - streamlit-star-rating==0.0.6
